- name: Build backend application
  docker_image:
    name: "{{ image_name }}"        # Docker image name backend_3
    tag: "{{ image_tag }}"
    source: build              # Docker image tag
    build:
      path: "{{ backend_path }}"  # Path to the Flask app directory
      dockerfile: Dockerfile   # Name of the Dockerfile
    state: present


- name: Ensures The backend container is running
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    ports:
      - "5000:5000"
    command: "npm start"
    networks:
      - name: yolom-network
    env:
      MONGODB_URI: "mongodb://app-mongo:27017/"